apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: daemonsets.apps.upccloud.com
spec:
  group: apps.upccloud.com  
  names:
    kind: DaemonSet
    listKind: DaemonSetList
    plural: daemonsets
    singular: daemonset
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
              selector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    additionalProperties:
                      type: string
              template:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      labels:
                        type: object
                        additionalProperties:
                          type: string
                  spec:
                    type: object
                    properties:
                      containers:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            image:
                              type: string
        required:
          - spec
